### PR TITLE
typo: brackets for consistency

### PR DESCRIPTION
**Pull request by lightonflux**
brackets for consistency

### CODE REVIEW

**Comment by VojtechMyslivec** [comment]
Alright :roll_eyes: 

But, please, squash it with your `patch-1` branch to have these 2 changes in one commit. Thanks

**Comment by lightonflux** [comment]
Done.

**Comment by VojtechMyslivec** [comment]
Well it's not like I thought. 

I have moved it to #17

**Comment by lightonflux** [comment]
> Well it's not like I thought.

Please tell me what you had in mind. I only know a little bit of git.

**Comment by VojtechMyslivec** [comment]
Never mind I have done it in be70bd5 - the credit still goes to you. I just want to have these two similar changes in one commit.

`squash` IMHO means join two (or more) commits into one. And yes, you can do it in several way (I.E *rebase* + *reset* + *amend* or *rebase* + *rebase -i* with *squash*/*fixup* and so on).

**Pull request closed without merging**
